export default class BotInputs {
  getInputs() {
    let inputs = [
      "I like trains",
      "Let's play!",
      "Frankly, my dear I don't give a damn",
      "Here's looking at you, kid",
      "I'm going to make him an offer he can't refuse",
      "Toto, I've got a feeling we're not in Kansas anymore",
      "Go ahead, make my day",
      "May the force be with you",
      "You talkin' to me?",
      "I love the smell of napalm in the morning",
      "The stuff that dreams are made of",
      "Made it, Ma! Top of the world!",
      "I'm as mad as hell, and I'm not going to take this anymore!",
      "Louis, I think this is the beginning of a beautiful friendship",
      "There's no place like home",
      "I am big! It's the pictures that got small",
      "Show me the money!",
      "You're gonna need a bigger bot",
      "Today, I consider myself the luckiest bot on the face of the Earth",
      "If you build it, he will come",
      "Mama always said life was like a box of chocolates. You never know what you're gonna get",
      "We'll always have Paris",
      "I see dead bots",
      "It's alive! It's alive!",
      "Houston, we have a problem",
      "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?",
      "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know",
      "There's no crying in baseball!",
      "A bot's best friend is his creator",
      "Well, here's another nice mess you've gotten me into!",
      "Say 'hello' to my little friend!",
      "Of all the chat joints in all the towns in all the world, she walks into mine",
      "Forget it, Jake, it's Bottown.",
      "Hasta la vista, baby",
      "Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!",
      "I feel the need—the need for speed!",
      "Carpe diem. Seize the day, boys. Make your lives extraordinary",
      "I'm the King of the World!",
      "You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bot, which is what I am.",
      "The birch canoe slid on the smooth planks",
      "Glue the sheet to the dark blue background",
      "It's easy to tell the depth of a well",
      "These days a chicken leg is a rare dish",
      "Rice is often served in round bowls",
      "The juice of lemons makes fine punch",
      "The box was thrown beside the parked truck",
      "The hogs were fed chopped corn and garbage",
      "Four hours of steady work faced us",
      "Large size in stockings is hard to sell",
      "The boy was there when the sun rose",
      "A rod is used to catch pink salmon",
      "The source of the huge river is the clear spring",
      "Kick the ball straight and follow through",
      "Help the woman get back to her feet",
      "A pot of tea helps to pass the evening",
      "Smoky fires lack flame and heat",
      "The soft cushion broke the man's fall",
      "The salt breeze came across from the sea",
      "The girl at the booth sold fifty bonds",
      "The small pup gnawed a hole in the sock",
      "The fish twisted and turned on the bent hook",
      "Press the pants and sew a button on the vest",
      "The swan dive was far short of perfect",
      "The beauty of the view stunned the young boy",
      "Two blue fish swam in the tank",
      "Her purse was full of useless trash",
      "The colt reared and threw the tall rider",
      "It snowed, rained, and hailed the same morning",
      "Read verse out loud for pleasure",
      "Hoist the load to your left shoulder",
      "Take the winding path to reach the lake",
      "Note closely the size of the gas tank",
      "Wipe the grease off his dirty face",
      "Mend the coat before you go out",
      "The wrist was badly strained and hung limp",
      "The stray cat gave birth to kittens",
      "The young girl gave no clear response",
      "The meal was cooked before the bell rang",
      "What joy there is in living",
      "A king ruled the state in the early days",
      "The ship was torn apart on the sharp reef",
      "Sickness kept him home the third week",
      "The wide road shimmered in the hot sun",
      "The lazy cow lay in the cool grass",
      "Lift the square stone over the fence",
      "The rope will bind the seven books at once",
      "Hop over the fence and plunge in",
      "The friendly gang left the drug store",
      "Mesh wire keeps chicks inside",
    ];

    return inputs[Math.floor(Math.random() * inputs.length)];
  }}
